### ISSUE TITLE
Cannot use bind type volume.

### ISSUE THREAD

**Issue by robojerk** [dockcenter/velocity#11]
I attempt to run this container but have the volume mounted as bind type.
`docker run -i --name mc-velocity --hostname mc-velocity --publish 25577:25577 --volume /home/MYUSER/docker/mc-velocity:/data:rw dockcenter/velocity:latest`
I just see errors that files cant be read, written or created in /data

I even tried as a docker-compose

```
version: "3.8"
services:
  mc-velocity:
    image: dockcenter/velocity:latest
    container_name: mc-velocity
    hostname: mc-velocity
    restart: unless-stopped
    ports:
      - 25577:25577
    volumes:
      - type: bind
        source: /home/MYUSER/docker/mc-velocity/data
        target: /data
```

If I omit the volume stuff, and let the docker create a volume it works....
`docker run -i --name mc-velocity --hostname mc-velocity --publish 25577:25577 dockcenter/velocity:latest`

**Comment by zax71** [comment]
Running in to the same issues. It seems that the server cannot write to the folder with the logs I'm getting. My docker-compose section for Velocity is below.


```yml
proxy:
    image: dockcenter/velocity:latest
    container_name: "proxy"
    ports:
      - "25577:25577"
    volumes:
      - ./Proxy/:/data/
 ```

**Comment by bdeb1337** [comment]
Sup guys, just ran into this as well.

If you add a user directive, it seems to run correctly:

`cat docker-compose.yml`
```
version: '3.5'

services:
  velocity:
    image: 'dockcenter/velocity:stable'
    restart: always
    user: '1000:1000'
    environment:
      JAVA_MEMORY: 512M
    ports:
      - '25577:25577'
    volumes:
      - './velocity:/data'
```

`$ docker compose logs -f`
```
velocity  | 2023-07-23 18:48:50,301 main WARN Advanced terminal features are not available in this environment
velocity  | [18:48:50 INFO]: Booting up Velocity 3.1.1...
velocity  | [18:48:50 INFO]: Loading localizations...
velocity  | [18:48:51 INFO]: Connections will use epoll channels, libdeflate (Linux x86_64) compression, OpenSSL 1.1.x (Linux x86_64) ciphers
velocity  | [18:48:51 WARN]: Player info forwarding is disabled! All players will appear to be connecting from the proxy and will have offline-mode UUIDs.
velocity  | [18:48:51 INFO]: Loading plugins...
velocity  | [18:48:51 INFO]: Loaded 0 plugins
velocity  | [18:48:51 INFO]: Listening on /0.0.0.0:25577
velocity  | [18:48:51 INFO]: Velocity and some of its plugins collect metrics and send them to bStats (https://bStats.org).
velocity  | [18:48:51 INFO]: bStats collects some basic information for plugin authors, like how many people use
velocity  | [18:48:51 INFO]: their plugin and their total player count. It's recommended to keep bStats enabled, but
velocity  | [18:48:51 INFO]: if you're not comfortable with this, you can opt-out by editing the config.txt file in
velocity  | [18:48:51 INFO]: the '/plugins/bStats/' folder and setting enabled to false.
velocity  | [18:48:51 INFO]: Done (0.93s)!
```

Kind regards.
